// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace Iboss.Models;

public partial class rakibContext : DbContext
{
    public rakibContext(DbContextOptions<rakibContext> options)
        : base(options)
    {
    }

    public virtual DbSet<tblEmployee> tblEmployees { get; set; }

    public virtual DbSet<tblEmployeeAttendance> tblEmployeeAttendances { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<tblEmployee>(entity =>
        {
            entity.HasKey(e => e.employeeId).HasName("PK__tblEmplo__C134C9C1CDDBDD6C");

            entity.ToTable("tblEmployee");

            entity.HasIndex(e => e.employeeCode, "UQ__tblEmplo__A33087FC11DB9B97").IsUnique();

            entity.Property(e => e.employeeId).ValueGeneratedNever();
            entity.Property(e => e.employeeCode)
                .HasMaxLength(10)
                .IsUnicode(false);
            entity.Property(e => e.employeeName)
                .HasMaxLength(255)
                .IsUnicode(false);
            entity.Property(e => e.employeeSalary).HasColumnType("decimal(10, 2)");
        });

        modelBuilder.Entity<tblEmployeeAttendance>(entity =>
        {
            entity.HasKey(e => new { e.employeeId, e.attendanceDate }).HasName("PK__tblEmplo__05B1243EBB69CA21");

            entity.ToTable("tblEmployeeAttendance");

            entity.Property(e => e.attendanceDate).HasColumnType("date");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}