// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Iboss.Models;

public partial class tblEmployeeAttendance
{
    public int employeeId { get; set; }

    public DateTime attendanceDate { get; set; }

    public bool? isPresent { get; set; }

    public bool? isAbsent { get; set; }

    public bool? isOffday { get; set; }
}