// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace Iboss.Models;

public partial class tblEmployee
{
    public int employeeId { get; set; }

    public string employeeName { get; set; }

    public string employeeCode { get; set; }

    public decimal? employeeSalary { get; set; }

    public int? supervisorId { get; set; }
}